implemented %c, %g and %p classes
jcgoble3/luapatt pull request #1
Opened 2020-04-10 13:50 UTC by NotJustAToy

Thank you for you hard work and this great package!
I try implement the following classes: %c, %g and %p.

2020-04-10 15:25 UTC, jcgoble3 commented
Wow, I had forgotten about this project. As a preliminary step, I have updated the .travis.yml file to test modern versions of Python. I have not looked at any of your code yet and will do so within the next few days (I'm currently very busy with schoolwork).

2020-04-10 15:28 UTC, jcgoble3 commented
Looks like the Travis config needs a bit more updating than I thought. Give me some time to work it out; I haven't used Travis in a while.

2020-04-10 15:41 UTC, jcgoble3 commented
Tests are now working again. I will schedule time to look at the code this weekend.

2020-04-10 16:04 UTC, NotJustAToy commented
Thank you!

2020-04-10 19:00 UTC, jcgoble3 commented
Out of curiosity, what do you use this package for? I wasn't aware that anyone actually used it. I created this mainly as a way to familiarize myself with Lua's pattern-matching code (written in C) and for my own amusement. I published it on PyPI only because it was reasonably complete, but didn't expect anyone to actually use it.

2020-04-11 01:35 UTC, jcgoble3 requested changes
Just two minor things in the code to alter before I'm ready to merge. Check the suggested changes in the review; they're minor enough that if you don't make the edits by tomorrow afternoon/evening (US time), I'll make them myself, but I want to give you the chance to do it first since it's your contribution.

I would also like to see a README update since this renders the first bullet point obsolete and applies them in a different way from what the second bullet point mentions. Again, if I don't get anything from you by tomorrow evening, I'll probably do this myself.

Also, as mentioned above, I'm interested to hear how you're using this. If people are legitimately using this, I'll clean it up a tad and get a real 1.0 release out, and possibly add some additional features depending on my available time.

2020-04-11 01:35 UTC, jcgoble3 commented on src/luapatt.py
> +__version__ = '0.9.0b6'
The version change should be reverted. I'll handle the version update myself as part of the release process, and the next release might be something different (such as 1.0).

```suggestion
__version__ = '0.9.0b5'
```

2020-04-11 01:35 UTC, jcgoble3 commented on tests/test_lua1_basics.py
> +    assert luapatt.match('  \n\r*&\n\r   xuxu  \n\n', '%g%g%g+') == 'xuxu'
I was going to insist on using the tests from the official Lua test suite, but you've already done that. Nice!

2020-04-11 01:35 UTC, jcgoble3 commented on tests/test_lua1_basics.py
> +    assert luapatt.match('Hello World!', '%p+') == '!'
This one doesn't seem to be tested in the Lua test suite, so I'm satisfied with this test for now.

2020-04-11 01:35 UTC, jcgoble3 commented on src/luapatt.py
> +            match = unicodedata.category(sc)[0] not in ('C', 'Z')
I don't like tuples of single characters. Please change the tuple to a string (like in the removed line 446).

```suggestion
            match = unicodedata.category(sc)[0] not in 'CZ'
```

2020-04-11 04:19 UTC, jcgoble3 commented
Apologies for the commit noise. I pushed the .travis.yml updates to my own develop branch and tweaked the README to change the minimum supported version of Python, and then GitHub complained about branches being out of sync, so I had to merge those into your branch. When this is ready to merge, I'll do a squash merge, so all these excess merge commits and stuff will go away and we'll end up with one nice, neat commit.

2020-04-11 08:49 UTC, NotJustAToy commented
I wrote a lua interpreter in python and want to use this package in the implementation of the standard string library. I already tested it on `pm.lua` from the stock test suite and all tests pass.

2020-04-11 15:29 UTC, jcgoble3 approved these changes

2020-04-11 15:32 UTC, jcgoble3 commented
A Lua interpreter in Python? Interesting. I've thought about doing the same, but never got around to actually starting it. Do you have the code open source? I'm interested to look at it if you do.

Anyway, everything looks good, and the check for `Mapping` instead of `dict` is good too. I'll merge this in a moment.

2020-04-11 15:35 UTC, merged

2020-04-11 16:25 UTC, NotJustAToy commented
I think I can show the code in a couple of weeks. I will definitely inform you about this. Thanks!